name: PlayerCrasherPlus
version: '${version}'

main: io.github.earth1283.playerCrasherPlus.PlayerCrasherPlus
api-version: '1.21'
load: STARTUP

authors: [ Earth1283 ]
description: Teaching a lesson to that one player that won't stop bothering you.

commands:
  crash:
    description: Sends an oversized packet at a player's client.
    usage: /<command> <player> [sizeMB]
    permission: playercrasherplus.crash

permissions:
  playercrasherplus.crash:
    description: Allows use of /crash
    default: op
